print ("Q1")
print ("Informe sua nota do 1° bimestre")
nota1 = int (input ())
print ("Informe sua nota do 2° bimestre")
nota2 = int (input ())
print ("Informe sua nota do 3° bimestre")
nota3 = int (input ())
print ("Informe sua nota do 4° bimestre")
nota4 = int (input ())
media = int (((nota1) + (nota2) + (nota3) + (nota4))/4)
print ("Sua média foi: " , (media))
if ((media)>=6): print ("Parabens!! Você foi aprovado!  C:")
elif ((media)<6 and (media)>2): print ("Não desanime!! Você está em prova final!  :)")
elif ((media)<=2) : print ("Você foi reprovado! não desista dos seus sonhos!!  ;)")
else: print ("Algo de errado não está certo, digite novamente por favor  :/")