print("Q4")
print ("Digite um número:")
x = int (input ())
print ("Digite um 2° número")
y = int (input ())
Quo = int (x/y)
resto = int (x%y)
print (("A divisão resulta em: "),(Quo),("o resto é ="),(resto))