print("Q5")
print ("Informe a altura:")
h = float (input ())
print ("Informe o raio")
r = float (input ())
baseCIL = float ((3.14) * (r ** 2))
volCIL = float ((3.14) * (baseCIL) * h)
print (("A base do cilindro é ="),(baseCIL))
print (("E o volume do cilindro é ="),(volCIL))