print("Q7")
print ("Informe o 1° número")
x1 = int (input ())
print ("Informe o 2° número")
y2 = int (input ())
soma = (x1+y2)
mult = (x1*y2)
div1p2 = (x1/y2)
div2p1 = (y2/x1)
print (("A soma destes valores é:"),(soma))
print (("O produto destes valores é:"),(mult))
print (("O quociente de"), (x1), ("por"), (y2), ("é:"), (div1p2))
print (("O quociente do"), (y2), ("por"), (x1), ("é:"), (div2p1))
